/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package aplikasi.penjualan;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dandy
 */
public class Jual extends javax.swing.JInternalFrame {
Sambung k= new Sambung();
ResultSet rs=null;
    /**
     * Creates new form Jual
     */
public void tampilkandata(){
DefaultTableModel tbjual = new DefaultTableModel();
        tbjual.addColumn("No_Transaksi");
        tbjual.addColumn("No_Pelanggan");
        tbjual.addColumn("Nama_Toko");
        tbjual.addColumn("Nama_Pelanggan");
        tbjual.addColumn("Tgl_Transaksi");
        tbjual.addColumn("Jenis_Barang");
        tbjual.addColumn("Harga");
        tbjual.addColumn("Jumlah");
        tbjual.addColumn("Total_Harga");
        tbjual.addColumn("Bayar");
        tbjual.addColumn("Kembali");
        
        
        try {
            rs=k.ambilData("select * from penjualan2 order by No_Transaksi");
            
            
            while (rs.next()) {
                tbjual.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)
                ,rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11)});
            }
           jTable1.setModel(tbjual);
           notransaksi.setText("");
        toko.setText("");
        nama.setText("");
        tgl.setText("");
        
        total.setText("");
        bayar.setText("");
        kmbli.setText("");
        plg.setText("");
        plg.setEnabled(true);
        notransaksi.requestFocus();
        notransaksi.setEnabled(true);
        toko.setEnabled(true);
        nama.setEnabled(true);
        jenis.setSelectedItem("Pandan Wangi");
        harga.setText("");
        jml_ju.setText("");
        

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Table Tidak Ditemukan");
        }
       
}

    public Jual() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox();
        cari = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        tmplkn = new javax.swing.JButton();
        smpn = new javax.swing.JButton();
        delet = new javax.swing.JButton();
        harga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jml_ju = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        kmbli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tgl = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        toko = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        notransaksi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        plg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel6.setText("Jenis_Beras");
        jLabel6.setToolTipText("");

        jenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pandan Wangi", "Rojolele", "Sentra Ramos", "C4" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/cr.jpg"))); // NOI18N
        cari.setText("CARI");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/ed.jpg"))); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        tmplkn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/tm.jpg"))); // NOI18N
        tmplkn.setText("TAMPILKAN");
        tmplkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmplknActionPerformed(evt);
            }
        });

        smpn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/sv.jpg"))); // NOI18N
        smpn.setText("SIMPAN");
        smpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smpnActionPerformed(evt);
            }
        });

        delet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/dt.jpg"))); // NOI18N
        delet.setText("DELETE");
        delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletActionPerformed(evt);
            }
        });

        jLabel7.setText("Harga");

        jLabel8.setText("Jumlah_Jual");

        jml_ju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jml_juActionPerformed(evt);
            }
        });
        jml_ju.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jml_juKeyPressed(evt);
            }
        });

        jLabel13.setText("Karung");

        jLabel10.setText("Total Harga");

        jLabel11.setText("Bayar");

        bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bayarKeyPressed(evt);
            }
        });

        jLabel12.setText("Kembali");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No_Transaksi", "No_Pelanggan", "Nama_Toko", "Nama_Pelanggan", "Tgl_Transaksi", "Jenis Beras", "Harga", "Jumlah ", "Total_Harga", "Bayar", "Kembali"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Tgl_Transakasi");

        jLabel3.setText("Nama_Pelanggan");

        jLabel5.setText("Nama_Toko");

        jLabel2.setText("No_Pelanggan");

        jLabel14.setText("No_Transaksi");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("INPUT DATA PENJUALAN");

        plg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plgActionPerformed(evt);
            }
        });
        plg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                plgKeyPressed(evt);
            }
        });

        jLabel9.setText("yyyy-mm-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plg, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(toko, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cari)
                                            .addComponent(smpn))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(delet)
                                            .addComponent(edit)))
                                    .addComponent(tmplkn))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel14)
                                .addGap(33, 33, 33)
                                .addComponent(notransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addGap(8, 8, 8)
                                .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(40, 40, 40)
                                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(94, 94, 94)
                                        .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(65, 65, 65)
                                        .addComponent(jml_ju, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(66, 66, 66)
                                        .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(67, 67, 67)
                                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(95, 95, 95)
                                        .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(87, 87, 87)
                                        .addComponent(kmbli, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14))
                    .addComponent(notransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(plg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(toko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(smpn)
                                .addComponent(delet))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cari)
                            .addComponent(edit))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel7)))
                    .addComponent(tmplkn))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jml_ju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel11))
                            .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel12))
                            .addComponent(kmbli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmplknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmplknActionPerformed
        // TODO add your handling code here:
        tampilkandata();
    }//GEN-LAST:event_tmplknActionPerformed

    private void smpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smpnActionPerformed
        // TODO add your handling code here:
        String notrx=notransaksi.getText();
        String noplg=plg.getText();
        String nmtk=toko.getText();
        String nm=nama.getText();
        String tglt=tgl.getText();
        String jnis=jenis.getSelectedItem().toString();
        String hrg=harga.getText();
        String jml=jml_ju.getText();
        String tot=total.getText();
        String byr=bayar.getText();
        String kmbl=kmbli.getText();

        boolean j = k.simpanData("insert into penjualan2 value('"+notrx+"','"+noplg+"','"+nmtk+"','"+nm+"','"+tglt+"'"
            + ",'"+jnis+"','"+hrg+"','"+jml+"','"+tot+"','"+byr+"','"+kmbl+"')");
        tampilkandata();
        
    }//GEN-LAST:event_smpnActionPerformed

    private void deletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletActionPerformed
        // TODO add your handling code here:
         int hasil = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin ingin Hapus?", "Yakin?", JOptionPane.YES_NO_OPTION);
        if (hasil == 0) {
        try{
        int baris=jTable1.getSelectedRow();
        String not=(String)jTable1.getModel().getValueAt(baris, 0);
        boolean j=k.simpanData("delete from penjualan2 where No_Transaksi='"+not+"'");
        tampilkandata();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "KLIK PADA TABLENYA");
        }
        }
        else{
            tampilkandata();
        }
    }//GEN-LAST:event_deletActionPerformed

    private void plgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_plgKeyPressed
        // TODO add your handling code here:
        String a=plg.getText();
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        try {
            rs=k.ambilData("select * from Pelanggan2 where No_Pelanggan='"+a+"'");
            
            
            if (rs.next()) {
                toko.setText(rs.getString(2));
                nama.setText(rs.getString(3));
            tgl.requestFocus();
          plg.setEnabled(false);   
          toko.setEnabled(false);
          nama.setEnabled(false);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Data Tidak Ditemukan");
            }
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Table Tidak Ditemukan");
        }
         }
    }//GEN-LAST:event_plgKeyPressed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        String nopl=notransaksi.getText();
        DefaultTableModel tbjual = new DefaultTableModel();
       tbjual.addColumn("No_Transaksi");
        tbjual.addColumn("No_Pelanggan");
        tbjual.addColumn("Nama_Toko");
        tbjual.addColumn("Nama_Pelanggan");
        tbjual.addColumn("Tgl_Transaksi");
        tbjual.addColumn("Jenis_Barang");
        tbjual.addColumn("Harga");
        tbjual.addColumn("Jumlah");
        tbjual.addColumn("Total_Harga");
        tbjual.addColumn("Bayar");
        tbjual.addColumn("Kembali");
        if(nopl.equals("")){
            JOptionPane.showMessageDialog(rootPane, "NO TRANSAKSI HARUS DI ISI", "INFORMASI", WIDTH, null);
                notransaksi.requestFocus();
        }
        else{
         try {
             rs=k.ambilData("Select * from Penjualan2 where No_Transaksi='"+nopl+"'");
             
            if (rs.next()) {
        plg.setText(rs.getString(2));
        toko.setText(rs.getString(3));
        nama.setText(rs.getString(4));
        tgl.setText(rs.getString(5));
        jenis.setSelectedItem(rs.getString(6));
        harga.setText(rs.getString(7));
        jml_ju.setText(rs.getString(8));
        total.setText(rs.getString(9));
        bayar.setText(rs.getString(10));
        kmbli.setText(rs.getString(11));

                            tbjual.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)
                            ,rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11)});
            jTable1.setModel(tbjual);
            notransaksi.setEnabled(false);
            plg.setEnabled(false);
            toko.setEnabled(false);
            nama.setEnabled(false);
            tgl.requestFocus();
            }          
            else{
                JOptionPane.showMessageDialog(rootPane, "Data Tidak Ditemukan");
                notransaksi.requestFocus();
            }
           } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Error Pengambilan Data ");
        }
         
        }
    }//GEN-LAST:event_cariActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
       
        String no=notransaksi.getText();
        String noplg=plg.getText();
        String nmtk=toko.getText();
        String nm=nama.getText();
        String tglt=tgl.getText();
        String jnis=jenis.getSelectedItem().toString();
        String hrg=harga.getText();
        String jml=jml_ju.getText();
        String tot=total.getText();
        String byr=bayar.getText();
        String kmbl=kmbli.getText();
        
        if((no.equals(""))||(noplg.equals("")||(nmtk.equals("")||(nm.equals("")
                ||(tglt.equals("")||(jnis.equals("")||(hrg.equals("")||(jml.equals("")||(tot.equals("")
                ||(byr.equals("")||(kmbl.equals(""))))))))))))
                 
            {
                JOptionPane.showMessageDialog(rootPane, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
                notransaksi.requestFocus();
            }
            else {
         boolean j=k.simpanData("Update Penjualan2 SET Tgl_Transaksi='"+tglt+"'," + "Jenis_Beras='"+jnis+"',"+
                "Harga='"+hrg+ "',"+"Jumlah_Jual='"+jml+"',"+"Total_Harga='"+tot+"',"+"Bayar='"+byr+"',"+"Kembali='"+kmbl+"'"+"Where No_Transaksi='"+no+"'");
        JOptionPane.showMessageDialog(rootPane, "Berhasil di Update");     
        tampilkandata();
        }
    }//GEN-LAST:event_editActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
        String a= jenis.getSelectedItem().toString();
        if("Pandan Wangi".equals(a)){
            harga.setText("250000");
            
        }
        else if("Rojolele".equals(a)){
            harga.setText("225500");
            
        }
        else if("Sentra Ramos".equals(a)){
            harga.setText("212000");
        }
        else {
            harga.setText("200000");
        }
    }//GEN-LAST:event_jenisActionPerformed

    private void jml_juKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jml_juKeyPressed

        // TODO add your handling code here:
        
        String a =harga.getText();
        String b=jml_ju.getText();
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             int c=Integer.parseInt(a);
        int d=Integer.parseInt(b);
        int y=c*d;
        
        total.setText(Integer.toString(y));
        bayar.requestFocus();
        }
       
    }//GEN-LAST:event_jml_juKeyPressed

    private void bayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyPressed
        // TODO add your handling code here:
        String a =total.getText();
        String b=bayar.getText();
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        int c=Integer.parseInt(a);
        int d=Integer.parseInt(b);
        int y=d-c;
        if(y<0){
            JOptionPane.showMessageDialog(rootPane, "Uang Anda Kurang");
        }
        else{
        kmbli.setText(Integer.toString(y));
        }
        }
    }//GEN-LAST:event_bayarKeyPressed

    private void plgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plgActionPerformed

    private void jml_juActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jml_juActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jml_juActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JButton cari;
    private javax.swing.JButton delet;
    private javax.swing.JButton edit;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jenis;
    private javax.swing.JTextField jml_ju;
    private javax.swing.JTextField kmbli;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField notransaksi;
    private javax.swing.JTextField plg;
    private javax.swing.JButton smpn;
    private javax.swing.JTextField tgl;
    private javax.swing.JButton tmplkn;
    private javax.swing.JTextField toko;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
