/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.penjualan;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dandy
 */
public class Pemasok extends javax.swing.JInternalFrame {
Sambung k= new Sambung();
ResultSet rs=null;
    /**
     * Creates new form Pemasok
     */
public void tampilkandata(){
DefaultTableModel tbpelanggan = new DefaultTableModel();
        tbpelanggan.addColumn("ID_Pemasok");
       tbpelanggan.addColumn("Nama");
        tbpelanggan.addColumn("Alamat");
        
        
        try {
            rs=k.ambilData("select * from pemasok2 order by ID_Pem");
            
            
            while (rs.next()) {
                tbpelanggan.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});
            }
           jTable2.setModel(tbpelanggan);
        id_pemasok.setText("");
        nm_pemasok.setText("");
        alamat.setText("");
        id_pemasok.requestFocus();
        id_pemasok.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Table Tidak Ditemukan");
        }
}
    public Pemasok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_pemasok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nm_pemasok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("INPUT DATA PEMASOK");

        jLabel2.setText("ID Pemasok");
        jLabel2.setToolTipText("");

        id_pemasok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                id_pemasokKeyPressed(evt);
            }
        });

        jLabel3.setText("Nama Pemasok");

        jLabel5.setText("Alamat");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/sv.jpg"))); // NOI18N
        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/dt.jpg"))); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/cr.jpg"))); // NOI18N
        jButton2.setText("CARI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/ed.jpg"))); // NOI18N
        jButton3.setText("EDIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/Gambar/tm.jpg"))); // NOI18N
        jButton5.setText("Tampilkan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID_Pemasok", "Nama", "Alamat"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id_pemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nm_pemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id_pemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nm_pemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_pemasokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_pemasokKeyPressed

    }//GEN-LAST:event_id_pemasokKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id=id_pemasok.getText();
        String nama=nm_pemasok.getText();
        String alamat2=alamat.getText();
       
        if((id.equals(""))||(nama.equals(""))||
                 (alamat2.equals("")))
                 
            {
                JOptionPane.showMessageDialog(rootPane, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
                id_pemasok.requestFocus();
            }
        else{
        boolean j = k.simpanData("insert into pemasok2 value('"+id+"','"+nama+"','"+alamat2+"')");
        tampilkandata();
       
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int hasil = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin ingin Hapus?", "Yakin?", JOptionPane.YES_NO_OPTION);
        if (hasil == 0) {
        try{
            
        
        int baris=jTable2.getSelectedRow();
        String id=(String)jTable2.getModel().getValueAt(baris, 0);
        boolean j=k.simpanData("delete from pemasok2 where Id_Pem='"+id+"'");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "KLIK PADA TABLENYA");
        }
        
        tampilkandata();
        }
        else{
            tampilkandata();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String id=id_pemasok.getText();
        String nma=nm_pemasok.getText();
        DefaultTableModel tbcari = new DefaultTableModel();
        
        tbcari.addColumn("ID_Pemasok");
       tbcari.addColumn("Nama");
        tbcari.addColumn("Alamat");
        if(id.equals("")){
         JOptionPane.showMessageDialog(rootPane, "ID Harus Di Isi");
        }
        else{
        try {
            rs=k.ambilData("Select * from Pemasok2 where Id_Pem='"+id+"'");           
            if (rs.next()) {               
             nm_pemasok.setText(rs.getString(2));
            alamat.setText(rs.getString(3));
            
                tbcari.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});
            jTable2.setModel(tbcari);
           id_pemasok.setEnabled(false);
           nm_pemasok.requestFocus();
            }
            
            else{
               JOptionPane.showMessageDialog(rootPane, "Data Tidak Ada");
               id_pemasok.requestFocus();
            }  
           
           
           
        } catch (Exception e) {
         JOptionPane.showMessageDialog(rootPane, "Terdapat Kesalahan");
        }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String id= id_pemasok.getText();
        String nama=nm_pemasok.getText();
        String alamat2=alamat.getText();
        if((id.equals(""))||(nama.equals(""))||
                 (alamat2.equals("")))
                 
            {
                JOptionPane.showMessageDialog(rootPane, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
                id_pemasok.requestFocus();
            }
        else{
        boolean j=k.simpanData("Update pemasok2 SET Nama='"+nama+"'," + "Alamat='"+alamat2+"'"+"Where Id_Pem='"+id+"'");
        JOptionPane.showMessageDialog(rootPane, "Berhasil di Update");
        tampilkandata();
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        tampilkandata();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField id_pemasok;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField nm_pemasok;
    // End of variables declaration//GEN-END:variables
}
